config/routes.rb
Rails.application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"
  get "my_account" => "users#show", :as => "my_account"
  root :to => "users#new"
  resources :users
  resources :sessions

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :users
end

app/models/host.rb
class Host < ActiveRecord::Base
  belongs_to :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :guests
  has_many :hosts
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
end

app/controllers/hosts_controller.rb
class HostsController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if session[:user_id]
      redirect_to users_path
    end
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to users_path, :notice => "Logged in!"
    else
      flash.now[:notice]= "Invalid email or password."
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Successfully logged out."
  end

  # private

  # def user_params
  #   params.require(:session).permit(:email, :password)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to users_path, :notice => "Signed up."
    else
      flash.now[:notice] = "Your submission is invalid."
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/hosts_helper.rb
module HostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-fixed navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand" href="#">WAITLESS</a> -->
      <%= link_to "Waitless", users_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Logged in as <%= current_user.email %></a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Settings <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <!-- <li><a href="#">Account Info</a></li> -->
            <li> <%= link_to "My Account", user_path(current_user.id) %> </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
         <li> <%= link_to('Logout', log_out_path) %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Waitless </title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <% if current_user  %>
    <%= render "layouts/header" %>
  <% else %>
    <%= link_to "Sign up", sign_up_path %> or
    <%= link_to "log in", log_in_path %>
  <% end %>
  
  <%= yield %>

  </body>
</html>

app/views/users/index.html.erb
<h1> Signed in!!!</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class = "error_messages">
      <p> Invalid submission. </p>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li> <%= message %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class = "field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class = "field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  
  <p class = "button"> 
    <%= f.submit %>
  </p>

<% end %>

app/views/users/show.html.erb
<h1> My Account </h1>
<ul>
  <li>
    <%= @user.email %>
  </li>
</ul>